### ISSUE TITLE
Use string for project id

### ISSUE THREAD

**Issue by zheli** [latitudesh/latitudesh-go#34]
I've reported a bug in the terraform repo (https://github.com/latitudesh/terraform-provider-latitudesh/issues/45) and I think it is caused by https://github.com/latitudesh/latitudesh-go/blob/62d89d9b73f83e200f44207d05eb9858c673a4d6/servers.go#L130

Would be great to fix it so it is usable again. Thank you!

**Comment by ynhummel** [comment]
Thank you for your comment, and I apologize for the late reply. I will look into this problem. Also, we are working on updating this project to address any mismatches that might occur

**Comment by esoubihe** [comment]
@zheli thank you for your contribution. This has been fixed on https://github.com/latitudesh/latitudesh-go/pull/37 and is now available on [0.2.6](https://github.com/latitudesh/latitudesh-go/releases/tag/v0.2.6). 

There's an open PR to fix this on the terraform provider [here](https://github.com/latitudesh/terraform-provider-latitudesh/pull/49), so I'm closing the issue here.

Again, thanks for opening an issue and please let us know if you're still finding problems with the SDK
